# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://172.28.0.1:46602"
moniker = "node-3"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://172.28.0.82:46657"

[p2p]
laddr = "tcp://172.28.0.82:46656"
seeds = "172.28.0.80:46656"
